{config_load file=$lang_file section="pacientes"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <div class="contenidos">
    {if $codigo == 0}
      <p>{#texto36#}</p>
    {else}
      <p>{#texto37#}</p>
      <p>{#texto38#}<a href={$req_base}index.php/cod.verpac/id.{$codigo}>{#texto39#}</a>{#texto40#}</p>
    {/if}
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
