{config_load file=$lang_file section="pacientes"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

  <div class="contenidos">
    {if $codigo == 1}
      <p>{#texto57#}</p>
    {else}
      <p>{#texto56#}</p>
    {/if}
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
