<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>{#tituloapp#}</title>
	<link href="{$req_base}css/estilos_aplicacion.css" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" href="{$img_path_base}favicon.ico" />
	<script language="JavaScript" src="{$req_base}js/gen_validatorv31.js" type="text/javascript"></script>
	<script language="JavaScript" src="{$req_base}js/utils.js" type="text/javascript"></script>
</head>

<body onLoad="loaded()">
	<div class="cabecera" >
	<img class="obj" src="{$req_base}file.php/logo" width="220" height="150" />
	<p>{#textoheaderapp#}</p>
    <p>{$fecha}</p>
	</div>
	<div class="salir">
	 <a href={$req_base}index.php/cod.logout><img class="salir" src="{$img_path_base}btn_salir.jpg" alt="Salir" /></a>
	</div>

{include file=$tpl_path_base|cat:"gbdapp/common/navbar.phtml"}
