{config_load file=$lang_file section="publicaciones"}

{include file=$tpl_path_base|cat:"common/header.phtml"}

<div class="contenedor">
  {if $codigo == 1}
      <span class="intro">{#intro#}</span>
      <p>{#actualizarok#}</p>
  {else}
      <span class="intro">{#error#}</span>
      <p>{#actualizarerror#}</p>
  {/if}
</div>

{include file=$tpl_path_base|cat:"common/footer.phtml"}