{config_load file=$lang_file section="tesis"}

{include file=$tpl_path_base|cat:"common/header.phtml"}

<div class="contenedor">
  <div class="col_izq">
			<p>{#texto2#}</p>
			<br /><br /><br /><br /><br /><br />
		</div>
  <div class="col_central">
    <span class="intro">{#intronueva#}</span>
    <p>{#texto1#}</p>
    <form enctype="multipart/form-data" method="POST" action="{$req_base}index.php/cod.nuevatesis">
    <fieldset><legend>{#datos#}</legend>
    {#titulo#} <input type="text" name="txtTitulo" /><br />
    {#autor#} <input type="text" name="txtAutor" /><br />
    {#directores#} <input type="text" name="txtDir" /><br />
    <input type="hidden" name="MAX_FILE_SIZE" value="20000000" />
    {#archivo#} <input type="file" name="fileTesis"/><br />
    </fieldset>
    <input type="submit" value={#aceptar#} />
    <input type="reset" value={#borrar#} />
    <input type="button" value={#cancelar#} onclick="document.location='{$req_base}index.php/cod.publi'"/>
    </form>
  </div>
</div>

{include file=$tpl_path_base|cat:"common/footer.phtml"}