<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>{#titulopagina#}</title>
	<link href="{$req_base}css/estilos_portal.css" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" href="{$img_path_base}favicon.ico" />
</head>

<body>
	<div class="cabecera">
		<table border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td rowspan="2" width="900px">
					<img src="{$img_path_base}logo_gbd.jpg" alt="Logo GlobalDent" width="700" height="150"/>
				</td>
				<td align="center">
				  {if $autenticado == 1}
				    <a href={$req_base}index.php/cod.logout><img src="{$img_path_base}btn_logout.jpg" alt="Logout" width="200" height="50" /></a>
				  {else}
					 <a href={$req_base}index.php/cod.login><img src="{$img_path_base}btn_usuarios.jpg" alt="Acceso Usuarios" width="200" height="50" /></a>
					{/if}
				</td>
			</tr>
			<tr>
				<td align="center">
					<a href={$req_base}index.php/cod.loginapp><img src="{$img_path_base}btn_clinicas.jpg" alt="Acceso Clinicas" width="200" height="50"  /></a>
				</td>
			</tr>
		</table>
	</div>
	
{include file=$tpl_path_base|cat:"common/navbar.phtml"}