<div class="pestanas">
		<ul>
		  <li><a href={$req_base}index.php/cod.home>
        {if $on == 1}
			   <img src="{$img_path_base}tab_inicio_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_inicio.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.servicios>
        {if $on == 2}
			   <img src="{$img_path_base}tab_servicios_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_servicios.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.publi>
        {if $on == 3}
			   <img src="{$img_path_base}tab_publi_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_publi.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.foros>
        {if $on == 4}
			   <img src="{$img_path_base}tab_foros_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_foros.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.usuarios>
        {if $on == 5}
			   <img src="{$img_path_base}tab_usuarios_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_usuarios.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.gestion>
        {if $on == 6}
			   <img src="{$img_path_base}tab_gestion_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_gestion.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.clientes>
        {if $on == 7}
			   <img src="{$img_path_base}tab_clientes_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_clientes.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.acerca>
        {if $on == 8}
			   <img src="{$img_path_base}tab_acerca_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_acerca.jpg"  height="45"/>
			{/if}
			</a></li>
			<li><a href={$req_base}index.php/cod.contacto>
        {if $on == 9}
			   <img src="{$img_path_base}tab_contacto_on.jpg"  height="49"/>
			 {else}
			   <img src="{$img_path_base}tab_contacto.jpg"  height="45"/>
			{/if}
			</a></li>
		</ul>
	</div>