{config_load file=$lang_file section="presupuestos"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

<div class="contenidos">
  <span class="intro">{#texto53#}</span>
  {if $codigo > 0}
    <p>{#texto54#}</p>
  {else}
    <p>{#texto55#}</p>
  {/if}
</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
