<div class="pac_info">
  <div class="logoclinica">
    <object data={$req_base}file.php/logo type="image/jpeg" width="100" height="110" ></object>
  </div>
  <div class="numpres">
  <p>{#texto12#}</p>
  <input type="text" name="txtNumero" value="{$presup.numero}"/>
  </div>
  {if is_array($paciente)}
  <p>{#texto8#}{$paciente.apellido}&nbsp;{$paciente.apellido2},&nbsp;{$paciente.nombre}</p>
  <p>{#texto9#}{$paciente.direccion}</p>
  <p>{#texto10#}{$paciente.telefono_fijo}/{$paciente.telefono_movil}</p>
  <p>{#texto11#}{$fecha}</p>
  {/if}
</div>