{config_load file=$lang_file section="presupuestos"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<script type="text/javascript">
{literal}
<!--
function borrar(num)
{
  var x = document.getElementById ("formulario");
  {/literal}
    x.action = "{$req_base}index.php/cod.borralineamp/id.{$paciente.id_paciente}/pres.{$presup.id_presupuesto}/num." + num;
  {literal}
  x.submit();
}
function linea()
{
  var x = document.getElementById ("formulario");
  {/literal}
    x.action = "{$req_base}index.php/cod.nuevalineamp/id.{$paciente.id_paciente}/pres.{$presup.id_presupuesto}";
  {literal}
  x.submit();
}
function servicio()
{
  var x = document.getElementsByName ("txtUnitario");
  var y = document.getElementsByName ("selServicio");
  var txt = y[0].options[y[0].selectedIndex].text;
  var primero = txt.lastIndexOf ("-");
  primero += 2;
  var ultimo = txt.lastIndexOf ("€");
  var cadena = txt.slice (primero, ultimo);
  x[0].value= cadena ;  
}
-->
{/literal}
</script>

<div class="contenidos">
  <div class="col_izq">
    <span class="intro">{#texto58#}</span>
    <p>{#texto59#}</p>
  </div>
  <div class="col_central">
    <span class="intro">{#texto57#}</span>
    <form id="formulario" enctype="multipart/form-data" method="POST" action={$req_base}index.php/cod.actualizapres/id.{$paciente.id_paciente}/pres.{$presup.id_presupuesto}>
    {include file=$tpl_path_base|cat:"gbdapp/presupuestos/cabecera.phtml"}
    <p>{#texto60#}</p>
    <table border="0" width="100%">
      <tr>
        <th colspan="3">{#texto13#}</th>
        <th colspan="3">&nbsp;</th>
      </tr>
      <tr>
        <td colspan="6">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="2">{#texto14#}</th>
        <th>{#texto56#}</th>
        <th>{#texto15#}</th>
        <th>{#texto16#}</th>
        
        <th>&nbsp;</th>
      </tr>
      <tr>
        <td colspan="6" class="lineahor">&nbsp;</td>
      </tr>
      {counter assign=numlinea start=1 skip=1}
      {assign var=total value=0}
        {if is_array($datos)}
          {foreach from=$datos key=llave item=linea}
            <tr>
              <td colspan="2">{$numlinea}.&nbsp;{$linea.servicio|default:#texto20#}</td>
              <td align="center">{$linea.unitario}</p>
              <td align="center">{$linea.cantidad}</td>
              <td align="right">{$linea.total} €.</td>
              <td><input type="button" value="{#borrar#}" onclick="borrar({$llave})">
            </tr>
          {counter}
          {math equation="x + y" x=$total y=$linea.total assign=total}
          {/foreach}
        {/if}
      <tr>
        <td colspan="2">{$numlinea}.&nbsp;
          {if is_array($servicios)}
            <select name="selServicio" onchange="servicio()">
              <option label="{#texto17#}" value=0>{#texto17#}</option>
              {html_options options=$servicios selected=0}
            </select>
          {else}
            {#texto18#}
            <a href={$req_base}index.php/cod.servicios>{#texto19#}</a>
          {/if}
        </td>
        <td><input type="text" name="txtUnitario" /></td>
        <td><input type="text" name="txtCuantos" value="1" /></td>
        <td><input type="button" value="{#aceptar#}" onclick="linea()"/></td>
      </tr>
      <tr>
        <td colspan="5" class="lineahor">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="3">{#texto16#}</th>
        <th>{$total} €.</th>
        <th>&nbsp;</th>
      </tr>
    </table>
    <b>{#texto21#}</b><p>{#texto22#} <input type="text" name="txtValidez" value="{$presup.validez|default:6}" />{#texto36#}</p>
    <ol>
      <li>{#texto23#}</li>
      <li>{#texto24#}</li>
    </ol>
    <b>{#texto25#}</b><p>{#texto26#}</p>
    <ol>
      <li>{#texto27#}</li>
      <li>{#texto28#}</li>
    </ol>
    <b>{#texto29#}</b><p>{#texto30#}</p>
    <p><b>{#texto31#}</b><input type="text" name="txtDuracion" value="{$presup.duracion|default:30}" />{#texto37#}</p>
    <p>{#texto33#}</p>
    <div class="firmas">
      <object data={$req_base}file.php/fd type="image/jpg" width="100" height="100"></object>
      {if isset($presup.extension)}
        <object data={$req_base}file.php/fpres/{$paciente.id_paciente}/{$presup.id_presupuesto}/{$presup.extension} type="image/{$presup.extension}" width="100" height="100"></object>
        <div class="inputfirma">
          <input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
          <input type="file" name="fileFirma" />
        </div>
      {else}
        <input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
        <input type="file" name="fileFirma" />
      {/if}
      <br />
      <p>{#texto34#}</p>
      <p>{#texto35#}</p>
    </div>   
      <input type="hidden" name="txtTotal" value="{$total}" />
      <input type="submit" value="{#texto38#}" />
      <input type="button" value="{#cancelar#}" onclick="document.location='{$req_base}index.php/cod.presupuestos/id.{$paciente.id_paciente}'">
    </form>
  </div>
</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}