{config_load file=$lang_file section="presupuestos"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<script type="text/javascript">
//{literal}
//<!--
function borrar(num)
{
  var x = document.getElementById ("formulario");
  //{/literal}
    x.action = "{$req_base}index.php/cod.borralineap/id.{$paciente.id_paciente}/num." + num;
  //{literal}
  x.submit();
}
function linea()
{
	//{/literal}
	var err1 = "{#error1#}<br />";
	var err2 = "{#error2#}<br />";
	var err3 = "{#error3#}<br />";
	var err4 = "{#error4#}<br />";
	var err5 = "{#error5#}<br />";
	var action = "{$req_base}index.php/cod.nuevalineap/id.{$paciente.id_paciente}";
	//{literal}
	var canSend = true;
	var err = "";
	var z = document.getElementsByName ("txtUnitario");
	var k = document.getElementsByName ("txtCuantos");
	var y = document.getElementsByName ("selServicio");
	z = z[0].value;
	k = k[0].value;
	y = y[0].selectedIndex;

	if(y == 0){
		err += err5;
		canSend = false;
	}
	var charPos = z.search("[^0-9]");
	if(z.length > 0){
		if(charPos >= 0){
			err += err3;
			canSend = false;	
		}
	} else {
		err += err1;
		canSend = false;
	}
	charPos = k.search("[^0-9]");
	if(k.length > 0){
		if(charPos >= 0){
			err += err4;
			canSend = false;	
		}
	} else {
		err += err2;
		canSend = false;
	}
	if(canSend){
	  var x = document.getElementById ("formulario");
	  x.action = action;
	  x.submit();
	} else {
		show_errs("formulario_errorloc", err);
	}
}

function servicio()
{
  var x = document.getElementsByName ("txtUnitario");
  var y = document.getElementsByName ("selServicio");
  if (y[0].selectedIndex != 0) {
	  var txt = y[0].options[y[0].selectedIndex].text;
	  var primero = txt.lastIndexOf ("-");
	  primero += 2;
	  var ultimo = txt.lastIndexOf ("€");
	  var cadena = txt.slice (primero, ultimo);
	  x[0].value= cadena ;  
  } else {
	x[0].value = 0;
  }
}
function firmar()
{
	if(document.Sign.isSigned()){
		document.Sign.clear();
	}
    document.Sign.setSignThickness(2);
    //{/literal}
    var nombre = "{$paciente.apellido}" + " " + "{$paciente.apellido2}" + ", " + "{$paciente.nombre}";
	document.Sign.signNowEx({$paciente.id_paciente},nombre,"none","none","{$paciente.direccion}","{$paciente.dni}",true);
	//{literal}
	if(document.Sign.isSigned()){
		var x = document.Sign.getString();
		var info = document.getElementsByName ("txtSignData");
		info[0].value = x;
	}
}
function getHashData()
{
	var hashstr = "";
	var line = document.getElementById("line");
	if (line != null){
		while(line.nodeName == "TR"
				&& line.attributes != null 
				&& line.attributes.getNamedItem("id") != null 
				&& line.attributes.getNamedItem("id").nodeValue == "line"){
			var cells = line.childNodes;
			var num = cells.length;
			for (var i = 0 ; i < num ; ++i){
				var aux = cells.item(i);
				if(aux.nodeName == "TD"){
					var cellNode = aux.childNodes[0];
					if(cellNode.nodeType == 3){
						//If is a text node
  						hashstr += trim(cellNode.data);
					}
				}
			}
			do {
				//While we find a text node, get next sibling looking for a row
				line = line.nextSibling;
			} while (line.nodeType == 3);
		}
	}
	hashstr += "N" + document.formulario.txtNumero.value + 
				"D" + document.formulario.txtDuracion.value + 
				"V" + document.formulario.txtValidez.value;
  	return hashstr;	
}
function checkIntegrityAndSubmit()
{
	//{/literal}
	var err1 = "{#texto64#}<br />";
	var err2 = "{#texto65#}<br />";
	var err3 = "{#texto67#}<br />";
	var err4 = "{#texto66#}<br />";
	var err7 = "{#error7#}<br />";
	var err8 = "{#error8#}<br />";
	var err9 = "{#error9#}<br />";
	var err10 = "{#error10#}<br />";
	var err11 = "{#error11#}<br />";
	var err12 = "{#error12#}<br />";
	//{literal}
	var err = "";
	var canSend = true;
	if(document.Sign.isSigned()){
		switch(document.Sign.verifyDocument()){
		case 0:
			break;
		case 1:
			err += err1;
			canSend = false;
			break;
		case 2: 
			err += err2;
			canSend = false;
			break;
		case 4:
			err += err4;
			canSend = false;
			break;
		case 3:
		default:
			err += err3;
			canSend = false;
			break;
		}
	} else {
		err += err4;
		canSend = false;
	}

	var z = document.getElementsByName ("txtNumero");
	var k = document.getElementsByName ("txtDuracion");
	var y = document.getElementsByName ("txtValidez");
	z = z[0].value;
	k = k[0].value;
	y = y[0].value;

	var charPos = z.search("[^0-9]");
	if(z.length > 0){
		if(charPos >= 0){
			err += err7;
			canSend = false;	
		}
	} else {
		err += err8;
		canSend = false;
	}
	charPos = k.search("[^0-9]");
	if(k.length > 0){
		if(charPos >= 0){
			err += err9;
			canSend = false;	
		}
	} else {
		err += err10;
		canSend = false;
	}
	charPos = y.search("[^0-9]");
	if(y.length > 0){
		if(charPos >= 0){
			err += err11;
			canSend = false;	
		}
	} else {
		err += err12;
		canSend = false;
	}
	if(canSend){
		document.getElementById ("formulario").submit();
	} else {
		show_errs("formulario_errorloc", err);
	}
}
-->
//{/literal}
</script>

<div class="contenidos">
  <div class="col_izq">
    <span class="intro">{#texto5#}</span>
    <p>{#texto6#}</p>
  </div>
  <div class="col_central">
    <span class="intro">{#texto7#}</span>
    <div id='formulario_errorloc' class='error_strings'></div>
    <form id="formulario" name="formulario" enctype="multipart/form-data" method="POST" action={$req_base}index.php/cod.guardapres/id.{$paciente.id_paciente}>
    {include file=$tpl_path_base|cat:"gbdapp/presupuestos/cabecera.phtml"}
    <table border="0" width="100%">
      <tr>
        <th colspan="3">{#texto13#}</th>
        <th colspan="3">&nbsp;</th>
      </tr>
      <tr>
        <td colspan="6">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="2">{#texto14#}</th>
        <th>{#texto56#}</th>
        <th>{#texto15#}</th>
        <th>{#texto16#}</th>
        
        <th>&nbsp;</th>
      </tr>
      <tr>
        <td colspan="6" class="lineahor">&nbsp;</td>
      </tr>
      {counter assign=numlinea start=1 skip=1}
      {assign var=total value=0}
        {if is_array($datos)}
          {foreach from=$datos key=llave item=linea}
            <tr id="line">
              <td colspan="2">{$numlinea}.&nbsp;{$linea.servicio|default:#texto20#}</td>
              <td>{$linea.unitario}</p>
              <td align="center">{$linea.cantidad}</td>
              <td align="right">{$linea.total} €.</td>
              <td><input type="button" value="{#borrar#}" onclick="borrar({$llave})">
            </tr>
          {counter}
          {math equation="x + y" x=$total y=$linea.total assign=total}
          {/foreach}
        {/if}
      <tr>
        <td colspan="2">{$numlinea}.&nbsp;
          {if is_array($servicios)}
            <select name="selServicio" onchange="servicio()">
              <option label="{#texto17#}" value=0>{#texto17#}</option>
              {html_options options=$servicios selected=0}
            </select>
          {else}
            {#texto18#}
            <a href={$req_base}index.php/cod.servicios>{#texto19#}</a>
          {/if}
        </td>
        <td><input type="text" name="txtUnitario" value="0"/></td>
        <td><input type="text" name="txtCuantos" value="1" /></td>
        <td><input type="button" value="{#aceptar#}" onclick="linea()"/></td>
      </tr>
      <tr>
        <td colspan="5" class="lineahor">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="3">{#texto16#}</th>
        <th>{$total} €.</th>
        <th>&nbsp;</th>
      </tr>
    </table>
    <b>{#texto21#}</b><p>{#texto22#} <input type="text" name="txtValidez" value="{$presup.validez|default:6}" />{#texto36#}</p>
    <ol>
      <li>{#texto23#}</li>
      <li>{#texto24#}</li>
    </ol>
    <b>{#texto25#}</b><p>{#texto26#}</p>
    <ol>
      <li>{#texto27#}</li>
      <li>{#texto28#}</li>
    </ol>
    <b>{#texto29#}</b><p>{#texto30#}</p>
    <p><b>{#texto31#}</b><input type="text" name="txtDuracion" value="{$presup.duracion|default:30}" />{#texto37#}</p>
    <p>{#texto33#}</p>
    <div class="firmas">
    <APPLET classid=clsid:8AD9C840-044E-11D1-B3E9-00805F499D93 code="integrisign.webclient.WebSign" width=125 height=65 name="Sign" codebase="{$req_base}lib/" archive="websignsunjvm.jar" MAYSCRIPT>
	  <PARAM NAME="borderstyle" VALUE="1" >
	  <PARAM NAME="scriptable" VALUE="true" >
	  <PARAM NAME="cache_option" VALUE="Plugin" >
	  <PARAM NAME="cache_archive" VALUE="websignsunjvm.jar" >
	  <PARAM NAME="cache_version" VALUE="7.5.0.3" >
	  {#error6#}
	</APPLET> 
	
      <input type="button" value="{#texto63#}" onclick="firmar()"/>
      <br />
      <p>{#texto35#}</p>
    </div>   
      <input type="hidden" name="txtSignData" value="{$presup.firma}"/>
      <input type="hidden" name="txtTotal" value="{$total}" />
      <input type="button" value="{#texto38#}" onclick="checkIntegrityAndSubmit()"/>
      <input type="button" value="{#cancelar#}" onclick="document.location='{$req_base}index.php/cod.presupuestos/id.{$paciente.id_paciente}'">
    </form>
  </div>
</div>

<script type="text/javascript">
//<!--
//{literal}
var s = document.Sign;
if (s != null){
	//{/literal}
	var str = "{$presup.firma}";
	//{literal}
	if(str.length > 0){
		s.openSign1(str);
	}
}
//{/literal}
-->
</script>


{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
