{config_load file=$lang_file section="presupuestos"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<script type="text/javascript">
{literal}
<!--
  function abrir(dir)
  {
    window.open(dir);
  }
-->
{/literal}
</script>

<div class="contenidos">
  <div class="col_central">
    <span class="intro">{#texto45#}</span>
    {if is_array($datos)}
    {include file=$tpl_path_base|cat:"gbdapp/presupuestos/cabeceraver.phtml"}
    <table border="0" width="100%">
      <tr>
        <th colspan="2">{#texto13#}</th>
        <th colspan="3">&nbsp;</th>
      </tr>
      <tr>
        <td colspan="5">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="2">{#texto14#}</th>
        <th>{#texto15#}</th>
        <th>{#texto16#}</th>
        <th>&nbsp;</th>
      </tr>
      <tr>
        <td colspan="5" class="lineahor">&nbsp;</td>
      </tr>
      {counter assign=numlinea start=1 skip=1}
        {if is_array($lineas)}
          {foreach from=$lineas key=llave item=linea}
            <tr>
              <td colspan="2">{$numlinea}.&nbsp;{$linea.servicio|default:#texto20#}</td>
              <td align="center">{$linea.cantidad}</td>
              <td align="right">{$linea.total} €.</td>
            </tr>
          {counter}
          {/foreach}
        {/if}
      <tr>
        <td colspan="5" class="lineahor">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="3">{#texto16#}</th>
        <th>{$datos.total} €.</th>
        <th>&nbsp;</th>
      </tr>
    </table>
    <b>{#texto21#}</b><p>{#texto22#} {$datos.validez} {#texto36#}</p>
    <ol>
      <li>{#texto23#}</li>
      <li>{#texto24#}</li>
    </ol>
    <b>{#texto25#}</b><p>{#texto26#}</p>
    <ol>
      <li>{#texto27#}</li>
      <li>{#texto28#}</li>
    </ol>
    <b>{#texto29#}</b><p>{#texto30#}</p>
    <p><b>{#texto31#}</b>{$datos.duracion} {#texto37#}</p>
    <p>{#texto33#}</p>
    <blockquote class="firmas">
      <img class="obj" src="{$req_base}file.php/fd" width="100" height="100" />
      {if isset($datos.extension)}
      <object data={$req_base}file.php/fpres/{$paciente.id_paciente}/{$datos.id_presupuesto}/{$datos.extension} type="image/{$datos.extension}" width="100" height="100"></object>
      {/if}
      <br />
      <p>{#texto34#}</p>
      <p>{#texto35#}</p>
    </blockquote>
  {else}
    <p>{#texto46#}</p>
  {/if}
  </div>
  {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_header.phtml"}
    {if is_array($datos)}
      <li><input type="button" value="{#texto48#}" onclick="abrir('{$req_base}index.php/cod.verpres/id.{$paciente.id_paciente}/pres.{$datos.id_presupuesto}/imp.1')" /></li>
      <li><a href={$req_base}index.php/cod.modpres/id.{$paciente.id_paciente}/pres.{$datos.id_presupuesto}>{#texto61#}</a></li>
      <li><a href={$req_base}index.php/cod.borrapres/id.{$paciente.id_paciente}/pres.{$datos.id_presupuesto}>{#texto47#}</a></li>
      <li><a href={$req_base}index.php/cod.verpac/id.{$paciente.id_paciente}>{#texto49#}</a></li>
    {/if}
  {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_footer.phtml"}
</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}