{config_load file=$lang_file section="conta"}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>{#tituloapp#}</title>
	<link href="{$req_base}css/estilos_aplicacion.css" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" href="{$img_path_base}favicon.ico">
</head>
<body class="imprimible">
      <br /><br />

      <span class="intro">{#texto4#}{$dias.hoy}</span>
      {assign var=total_tarj value=0}
      {assign var=total_efect value=0}
      {if is_array($visitas)}
        {counter assign=total_vis start=0 skip=1}
        <table border="0" cellspadding="0" cellspacing="2" width="100%">
          <tr>
            <th>{#texto7#}</th>
            <th>{#texto8#}</th>
            <th>{#texto9#}</th>
            <th>{#texto10#}</th>
            <th>{#texto6#}</th>
            <th>&nbsp;</th>
          </tr>
          <tr>
            <td colspan="6">&nbsp;</td>
          </tr>
        {foreach from=$visitas item=visita}
          {assign var=linea value=0}
          <tr>
            <td>{$visita.paciente}</td>
            <td>
              {if isset ($visita.tratamiento)}
                {$visita.tratamiento}
              {else}
                {#texto24#}
              {/if}
            </td>
            <td class="pendiente" align="center">{$visita.precio} €</td>
            <td align="center">{$visita.pagos.tarj}/{$visita.pagos.efect}</td>
            {math equation="x + y" x=$visita.pagos.tarj y=$total_tarj assign=total_tarj}
            {math equation="x + y" x=$visita.pagos.efect y=$total_efect assign=total_efect}
            {if $visita.saldo < 0}
              <td align="center" class="pendiente">{$visita.saldo}</td>
            {else}
              <td align="center">{$visita.saldo}</td>
            {/if}
          </tr>
          <tr>
            <td colspan="6">&nbsp;</td>
          </tr>
          {counter}
        {/foreach}
        </table>
      {else}
        <p>{#texto5#}</p>
      {/if}
      
      {if is_array ($pagos)}
        <table border="0" cellspacing="2" cellspadding="0" width="98%">
          <tr>
            <th colspan="3">{#texto28#}</th>
          </tr>
          <tr>
            <th colspan="3" class="lineahor">&nbsp;</th>
          </tr>
          <tr>
            <th>{#texto7#}</th>
            <th>{#texto10#}</th>
            <th>{#texto6#}</th>
          </tr>
          {foreach from=$pagos item=pago}
            <tr>
              <td>{$pago.apellido} {$pago.apellido2}, {$pago.nombre}</td>
              <td align="center">{$pago.tarj}/{$pago.efect}</td>
              {math equation="x + y" x=$pago.tarj y=$total_tarj assign=total_tarj}
              {math equation="x + y" x=$pago.efect y=$total_efect assign=total_efect}
            {if $pago.saldo <= 0}
              <td align="center" class="pendiente">{$pago.saldo}</td>
            {else}
              <td align="center">{$pago.saldo}</td>
            {/if}
            </tr>
            <tr>
              <td colspan="3">&nbsp;</td>
            </tr>
          {/foreach}
        </table>
      {else} 
        <p>{#texto27#}</p>
      {/if}
        <table border="0" cellspacing="2" width="98%"> 
          <tr>
            <td colspan="7">&nbsp;</td>
          </tr>
          <tr>
            <th colspan="7">{#texto14#}</th>
          </tr>
          <tr>
            <td colspan="7">&nbsp;</td>
          </tr>
          <tr>
            <th colspan="2">{#texto11#}</th>
            <th colspan="2">{#texto29#}</th>
            <th>&nbsp;</th>
            <th colspan="2">{#texto12#}</th>
          </tr>
          <tr>
            <td colspan="7">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="2" align="center">{$total_vis}</td>
            <td colspan="2" align="center">{$total_tarj} €</td>
            <td>&nbsp;</td>
            <td colspan="2" align="center">{$total_efect} €</td>
          </tr>
        </table>

        <br /><br />

</body>
</html>
