{config_load file=$lang_file section="conta"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<style type="text/css">@import url({$req_base}js/calendario/estilos/calendar-system.css);</style>
<script type="text/javascript" src="{$req_base}js/calendario/calendar.js"></script>
<script type="text/javascript" src="{$req_base}js/calendario/calendar-es.js"></script>
<script type="text/javascript" src="{$req_base}js/calendario/calendar-setup.js"></script>

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

  <div class="contenidos">
    <div class="col_central">
      <span class="intro">{#texto4#}{$dias.hoy}</span>
      {assign var=total_tarj value=0}
      {assign var=total_efect value=0}
      {if is_array($visitas)}
        {counter assign=total_vis start=0 skip=1}
        <table border="0" cellspadding="0" cellspacing="2" width="100%">
          <tr>
            <th>{#texto7#}</th>
            <th>{#texto8#}</th>
            <th>{#texto9#}</th>
            <th>{#texto10#}</th>
            <th>{#texto6#}</th>
          </tr>
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
        {foreach from=$visitas item=visita}
        {if $visita.fsa != 1}
          {assign var=linea value=0}
          <tr>
            <td><a href={$req_base}index.php/cod.verpac/id.{$visita.id_paciente}>{$visita.paciente}</a></td>
            <td>
              {if isset ($visita.tratamiento)}
                {$visita.tratamiento}
              {else}
                {#texto24#}
              {/if}
            </td>
            <td class="pendiente" align="center">{$visita.precio} €</td>
            <td align="center">{$visita.pagos.tarj}/{$visita.pagos.efect}</td>
            {math equation="x + y" x=$visita.pagos.tarj y=$total_tarj assign=total_tarj}
            {math equation="x + y" x=$visita.pagos.efect y=$total_efect assign=total_efect}
            {if $visita.saldo < 0}
              <td align="center" class="pendiente">{$visita.saldo}</td>
            {else}
              <td align="center">{$visita.saldo}</td>
            {/if}
          </tr>
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
          {counter}
          {/if}
        {/foreach}
        </table>
      {else}
        <p>{#texto5#}</p>
      {/if}
      {if is_array ($pagos)}
        <table border="0" cellspacing="2" cellspadding="0" width="98%">
          <tr>
            <th colspan="3">{#texto28#}</th>
          </tr>
          <tr>
            <th colspan="3" class="lineahor">&nbsp;</th>
          </tr>
          <tr>
            <th>{#texto7#}</th>
            <th>{#texto10#}</th>
            <th>{#texto6#}</th>
          </tr>
          {foreach from=$pagos item=pago}
            <tr>
              <td><a href={$req_base}index.php/cod.verpac/id.{$pago.id_paciente}>{$pago.paciente}</a></td>
              <td align="center">{$pago.tarj}/{$pago.efect}</td>
              {math equation="x + y" x=$pago.tarj y=$total_tarj assign=total_tarj}
              {math equation="x + y" x=$pago.efect y=$total_efect assign=total_efect}
            {if $pago.saldo < 0}
              <td align="center" class="pendiente">{$pago.saldo}</td>
            {else}
              <td align="center">{$pago.saldo}</td>
            {/if}
            </tr>
            <tr>
              <td colspan="3">&nbsp;</td>
            </tr>
          {/foreach}
        </table>
      {else} 
        <p>{#texto27#}</p>
      {/if}
        <table border="0" cellspacing="2" width="98%"> 
          <tr>
            <td colspan="7">&nbsp;</td>
          </tr>
          <tr>
            <th colspan="7">{#texto14#}</th>
          </tr>
          <tr>
            <td colspan="7">&nbsp;</td>
          </tr>
          <tr>
            <th colspan="2">{#texto11#}</th>
            <th colspan="2">{#texto29#}</th>
            <th>&nbsp;</th>
            <th colspan="2">{#texto12#}</th>
          </tr>
          <tr>
            <td colspan="7">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="2" align="center">{$total_vis}</td>
            <td colspan="2" align="center">{$total_tarj} €</td>
            <td>&nbsp;</td>
            <td colspan="2" align="center">{$total_efect} €</td>
          </tr>
        </table>
        
    </div>
    {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_header.phtml"}
      <div id="calendar-container" class="calendario"></div>
      <li><a href={$req_base}index.php/cod.vercaja/f.{$dias.mannana}>{#texto19#}</a></li>
      <li><a href={$req_base}index.php/cod.vercaja>{#texto20#}</a></li>
      <li><a href={$req_base}index.php/cod.vercaja/f.{$dias.ayer}>{#texto21#}</a></li>
      <li><a href={$req_base}index.php/cod.verpendientes>{#texto22#}</a></li>
    <script type="text/javascript">
    {literal}
    function dateChanged(calendar) {
    // Beware that this function is called even if the end-user only
    // changed the month/year. In order to determine if a date was
    // clicked you can use the dateClicked property of the calendar:
    if (calendar.dateClicked) {
    // OK, a date was clicked, redirect to /yyyy/mm/dd/index.php
    var y = calendar.date.getFullYear();
    var m = calendar.date.getMonth(); // integer, 0..11
    m = m+1;
    var d = calendar.date.getDate(); // integer, 1..31
    // redirect...
    {/literal}
    document.location = "{$req_base}index.php/cod.vercaja/f." + d + "-" + m + "-" + y;
    {literal}
    }
    };
    Calendar.setup(
    {
    flat : "calendar-container", // ID of the parent element
    flatCallback : dateChanged, // our callback function
    date : "{/literal}{$dias.cal}{literal}"
    }
    );
    {/literal}
    </script>
    {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_footer.phtml"}
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
