{config_load file=$lang_file section="conta"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<script type="text/javascript">
{literal}
<!--
function pagar (idp)
{
	//{/literal}
	var err1 = "{#error3#}<br />";
	var err2 = "{#error4#}<br />";
	var err3 = "{#error1#}<br />";
	var err4 = "{#error2#}<br />";
	//{literal}
	var err = "";
	var canSend = true;
	var x = document.getElementById (idp + "Tarj").value;
	var y = document.getElementById (idp + "Met").value;

	var charPos = x.search("[^0-9]");
	if(x.length > 0){
		if(charPos >= 0){
			err += err1;
			canSend = false;	
		}
	} else {
		err += err2;
		canSend = false;
	}
	charPos = y.search("[^0-9]");
	if(y.length > 0){
		if(charPos >= 0){
			err += err3;
			canSend = false;	
		}
	} else {
		err += err4;
		canSend = false;
	}
	if(canSend){
		document.fpago.idpaciente.value = idp;
		document.fpago.tarjeta.value = x;
		document.fpago.efectivo.value = y;
		document.fpago.submit();
	} else {
		show_errs("formulario_errorloc", err);
	}
}
-->
{/literal}
</script>
  <div class="contenidos">
    <div class="col_central">
      <span class="intro">{#texto15#}</span>
       <div id='formulario_errorloc' class='error_strings'></div>
      {if is_array($datos)}
        <p>{#texto16#}</p>
        {assign var=total_pend value=0}
        {counter assign=total_vis start=0 skip=1}
        <table cellspadding="0" cellspacing="2" border="0" width="98%">
          <tr>
            <th>{#texto7#}</th>
            <th>{#texto6#}</th>
            <th>{#texto10#}</th>
          </tr>
          <tr>
            <td colspan="3" class="lineahor">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="3">&nbsp;</td>
          </tr>
        {foreach from=$datos item=paciente}
          <tr>
            <td><a href={$req_base}index.php/cod.verpac/id.{$paciente.id_paciente}>{$paciente.apellido} {$paciente.apellido2}, {$paciente.nombre}</a></td>
            <td class="pendiente" align="center">{$paciente.saldo} €.</td>
            {math equation="x + y" x=$paciente.saldo y=$total_pend assign=total_pend}
            <td align="center"> 
              <input type="text" id="{$paciente.id_paciente}Tarj" size="5" value="0"/>
              <input type="text" id="{$paciente.id_paciente}Met" size="5" value="0"/> 
              <input type="button" value={#texto25#} onclick="pagar({$paciente.id_paciente})"/>
            </td>
          </tr>
          <tr>
            <td colspan="3">&nbsp;</td>
          </tr>
          {counter}
        {/foreach}
          <tr>
            <td colspan="3">&nbsp;</td>
          </tr>
          <tr>
            <th colspan="3">{#texto18#}</th>
          </tr>
          <tr>
            <td colspan="3" class="lineahor">&nbsp;</td>
          </tr>
          <tr>
            <th>{#texto11#}</th>
            <th colspan="2">{#texto13#}</th>
          </tr>
          <tr>
            <td colspan="3">&nbsp;</td>
          </tr>
          <tr>
            <td align="center">{$total_vis}</td>
            <td class="pendiente" colspan="2" align="center">{$total_pend} €</td>
          </tr>
        </table>
        <form name="fpago" enctype="multipart/form-data" action="{$req_base}index.php/cod.pagavisita">
          <input type="hidden" name="idpaciente" value="0" />
          <input type="hidden" name="efectivo" value="0" />
          <input type="hidden" name="tarjeta" value="0" />
        </form>
      {else}
        <p>{#texto17#}</p>
      {/if}
    </div>
    {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_header.phtml"}
      <li><a href={$req_base}index.php/cod.vercaja>{#texto23#}</a></li>
    {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_footer.phtml"}
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
