{config_load file=$lang_file section="personal"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

<div class="contenidos">
    <span class="intro">{#texto70#}</span>
    <div class="inicio">
      <span class="intro">{#texto1#}</span>
      <ul>
        <li><a href={$req_base}index.php/cod.suscripcion>{#texto71#}</a></li>
        <li><a href={$req_base}index.php/cod.log>{#texto72#}</a></li>
        <li><a href={$req_base}index.php/cod.datosclinica>{#texto73#}</a></li>
        <li><a href={$req_base}index.php/cod.copia>{#texto74#}</a></li>
      </ul>
    </div>
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
