{config_load file=$lang_file section="noautorizado"}

{include file=$tpl_path_base|cat:"/common/header.phtml"}

<div class="contenedor">
  <span class="intro">{#intro#}</span><br />
  <p>{#texto#}</p>
  <p>{#texto1#}
  <a href={$req_base}index.php/cod.login><img src="{$img_path_base}btn_usuarios.jpg" alt="boton acceso" height="50" align="middle"/> </a>
  </p>
</div>

{include file=$tpl_path_base|cat:"/common/footer.phtml"}
