{config_load file=$lang_file section="usuarios"}

{include file=$tpl_path_base|cat:"/common/header.phtml"}

  <div class="contenedor">
		<div class="col_central">
		  <span class="intro">{#texto15#}</span>
		  <p>{#texto33#}</p>
		  {if is_array ($datos)}
		    <table border="0" width="98%">
		      <tr>
		        <th colspan="2">{#texto19#}</th>
            <th>{#texto31#}</th>
            <th>{#texto32#}</th>  
		      </tr>
		      <tr><td colspan="4" class="lineahor">&nbsp;</td></tr>
		      {foreach from=$datos item=pago}
		        <tr>
              <td colspan="2">
                <a href={$req_base}index.php/cod.verfichaadmin/id.{$pago.id_usuario}>{$pago.usuario}</a>
              </td>
              <td>{$pago.fecha}</td>
              <td>{$pago.importe} €.</td>
            </tr> 
		      {/foreach}
		    </table>
		  {else}
		    <p>{#texto30#}</p> 
		  {/if}
	 </div>
	 {include file=$tpl_path_base|cat:"common/recuadro_header.phtml"}
		  <li><a href={$req_base}index.php/cod.usuarios>{#volver#}</a></li>
		{include file=$tpl_path_base|cat:"common/recuadro_footer.phtml"}
	</div>

{include file=$tpl_path_base|cat:"/common/footer.phtml"}