{config_load file=$lang_file section="personal"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <div class="contenidos">
    {if $codigo == 0}
      <p>{#texto43#}</p>
    {else}
      <p>{#texto44#}</p>
      <p>{#texto31#}<a href={$req_base}index.php/cod.verpers/id.{$codigo}>{#texto32#}</a>{#texto33#}</p>
    {/if}
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
