{config_load file=$lang_file section="personal"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

  <div class="contenidos">
    <div class="inicio">
      <span class="intro">{#texto1#}</span>
      <ul>
        {if $privilegios == 4}
          <li><a href={$req_base}index.php/cod.nuevoempleado>{#texto2#}</a></li>
        {/if}
        <li><a href={$req_base}index.php/cod.buscaempleados>{#texto3#}</a></li>
        <li><a href={$req_base}index.php/cod.listaempleados>{#texto4#}</a></li>
      </ul>
    </div>
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
