{config_load file=$lang_file section="agenda"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

<div class="contenidos">
  {if $codigo >= 1}
    <p>{#texto8#}</p>
    <p>{#texto29#}<a href={$req_base}index.php/cod.agenda/dia.{$fecha}>{#texto30#}</a>{#texto31#}</p>
  {elseif $codigo == -1}
    {#texto25#}
  {else}
    {#texto9#}
  {/if}
</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}