{config_load file=$lang_file section="conf"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<div class="contenidos">
  <div class="col_central">
    <span class="intro">{#texto9#}</span>
    {if $codigo > 0}
      <p>{#texto15#}</p>
      <a href={$req_base}index.php/cod.servicios>{#texto17#}</a>
    {else}
      <p>{#texto16#}</p>
    {/if}
  </div>

</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}