{config_load file=$lang_file section="conf"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

<div class="contenidos">
  <div class="col_central">
    <span class="intro">{#texto18#}</span>
    {if $codigo > 0}
      <p>{#texto19#}</p>
    {else}
      <p>{#texto20#}</p>
    {/if}
      <a href={$req_base}index.php/cod.servicios>{#texto17#}</a>
  </div>

</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}