{config_load file=$lang_file section="conf"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

  <div class="contenidos">
    <div class="col_izq">
      <span class="intro">{#texto38#}</span>
      <p>{#texto39#}</p>
    </div>
    <div class="col_central">
      <span class="intro">{#texto40#}</span>
      <p>{#texto41#}</p>
      <div id='clinica_errorloc' class='error_strings'></div>  
      <form name="clinica" enctype="multipart/form-data" method="POST" action={$req_base}index.php/cod.actualizadatosclinica>
      <fieldset><legend>{#texto40#}</legend>
        <p>{#texto42#}<p><input type="text" name="txtNombre" value="{$datos.nombre}" /><br />
        <p>{#texto43#}<p><input type="text" name="txtEspecialidad" value="{$datos.especialidad}" /><br />
        <p>{#texto44#}<p><input type="text" name="txtNif" value="{$datos.nif}" /><br />
        <p>{#texto45#}<p><input type="text" name="txtDireccion" value="{$datos.direccion}" /><br />
        <p>{#texto46#}<p><input type="text" name="txtCP" value="{$datos.cp}" /><br />
        <p>{#texto47#}<p><input type="text" name="txtCiudad" value="{$datos.ciudad}" /><br />
        <p>{#texto48#}<p>
          {if is_array($provincias)}
            <select name="selProv">
            <option label="{#texto49#}" value="0">{#texto49#}</option>
            {html_options options=$provincias selected=$datos.id_provincia}
            </select>
          {else}
            <p>{#texto50#}</p>
          {/if}<br />
        <p>{#texto51#}<p><input type="text" name="txtTelefono" value="{$datos.telefono}" /><br />
      </fieldset>
      <fieldset><legend>{#texto52#}</legend>
        <p>{#texto53#}<p><input type="text" name="txtGabinetes" value="{$datos.gabinetes}" /><br />
        <p>{#texto101#}<p><input type="text" name="txtRegSanidad" value="{$datos.reg_sanidad}" /><br />
      </fieldset>
        <input type="submit" value={#aceptar#} />
        <input type="reset" value={#borrar#} />
        <input type="button" value={#cancelar#} onclick="document.location='{$req_base}index.php/cod.conf'" /> 
      </form>
    </div>
  </div>
  
  <script type="text/javascript">
<!--
	var validator = new Validator("clinica");
	validator.addValidation("txtNombre", "req", "{#error0#}");
	validator.addValidation("txtNombre", "maxlen=200", "{#error1#}");
	validator.addValidation("txtEspecialidad", "maxlen=200", "{#error2#}");
	validator.addValidation("txtNif", "req", "{#error3#}");
	validator.addValidation("txtNif", "maxlen=9", "{#error4#}");
	validator.addValidation("txtDireccion", "maxlen=200", "{#error5#}");
	validator.addValidation("txtCP", "maxlen=5", "{#error6#}");
	validator.addValidation("txtCP", "num", "{#error7#}");
	validator.addValidation("txtCiudad", "maxlen=200", "{#error8#}");
	validator.addValidation("selProv", "dontselect=0", "{#error9#}");
	validator.addValidation("txtTelefono", "num", "{#error10#}");
	validator.addValidation("txtTelefono", "maxlen=13", "{#error11#}");
	validator.addValidation("txtGabinetes", "num", "{#error12#}");
	validator.addValidation("txtGabinetes", "maxlen=2", "{#error13#}");
	validator.addValidation("txtRegSanidad", "req", "{#error14#}");
	validator.EnableOnPageErrorDisplaySingleBox();
	validator.EnableMsgsTogether();
//-->
</script>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
