{config_load file=$lang_file section="conf"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <div class="contenidos">
    <div class="col_central">
      <span class="intro">{#texto103#}</span>
      <p>{#texto104#}</p>
      {if is_array($datos)}
        <div class="tablabusqueda">
          <div class="lineabusqueda">
            <div class="primera">{#texto105#}</div>
            <div class="tratamiento">{#texto106#}</div>
            <div class="indentar">&nbsp;</div>
          </div>
        {foreach from=$datos item=grupo}
          <div class="lineabusqueda">
            <div class="lineaopts">
              <a href={$req_base}index.php/cod.borragrupoimg/id.{$grupo.id_grupo_imagenes}><img src={$img_path_base}icoborrar.ico alt="{#borrar#}" width="16" height="16" title="{#borrar#}" /></a>
            </div>
            <div class="primera">{$grupo.nombre}</div>
            <div class="tratamiento">{$grupo.descripcion}</div>
          </div>
        {/foreach}
        </div>
      {else}
        <p>{#texto25#}</p>
      {/if}
    </div>
    {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_header.phtml"}
    <li><a href={$req_base}index.php/cod.nuevogrupoimg>{#texto107#}</a></li>
  {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_footer.phtml"}
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
