{config_load file=$lang_file section="conf"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <div class="contenidos">
    <div class="col_central">
      <span class="intro">{#texto81#}</span>
      {if $codigo > 0}
        <p>{#texto82#}</p>
        <p>{#texto71#}<a href={$req_base}index.php/cod.vertipocons/id.{$codigo}>{#texto72#}</a>{#texto73#}</p>
      {else}
        <p>{#texto83#}</p>
      {/if}
    </div>
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
