{config_load file=$lang_file section="conf"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <div class="contenidos">
    <div class="col_izq">
      <span class="intro">{#texto64#}</span>
      <p>{#texto65#}</p>
    </div>
    <div class="col_central">
      <span class="intro">{#texto66#}</span>
      <p>{#texto67#}</p>
      <form enctype="multipart/form-data" method="POST" action={$req_base}index.php/cod.altatipocons>
        <p>{#texto68#}<input type="text" name="txtNombre" /></p><br />
        <p>{#texto69#}</p><textarea name="txtTexto" cols="80" rows="100"></textarea><br />
        <input type="submit" value={#aceptar#} />
        <input type="reset" value={#borrar#} />
        <input type="button" value={#cancelar#} onclick="document.location='{$req_base}index.php/cod.tipocons'">
      </form>
    </div>
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
