{config_load file=$lang_file section="conf"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<script type="text/javascript" src="{$req_base}js/fckeditor/fckeditor.js"></script>
  <script type="text/javascript">
  <!--
  {literal}
  function FCKeditor_OnComplete( editorInstance )
  {
  	editorInstance.Events.AttachEvent( 'OnBlur'	, FCKeditor_OnBlur ) ;
  	editorInstance.Events.AttachEvent( 'OnFocus', FCKeditor_OnFocus ) ;
  }

  function FCKeditor_OnBlur( editorInstance )
  {
  	editorInstance.ToolbarSet.Collapse() ;
  }

  function FCKeditor_OnFocus( editorInstance )
  {
  	editorInstance.ToolbarSet.Expand() ;
  }
  function loaded(){}
  {/literal} 
  // -->
  </script>

  <div class="contenidos">
    <div class="col_izq">
      <span class="intro">{#texto64#}</span>
      <p>{#texto65#}</p>
    </div>
    <div class="col_central">
      <span class="intro">{#texto66#}</span>
      <p>{#texto67#}</p>
      <form enctype="multipart/form-data" method="POST" action={$req_base}index.php/cod.altatipocons>
        <p>{#texto68#}<input type="text" name="txtNombre" /></p><br />
        <p>{#texto69#}</p>
        <script type="text/javascript">
            var oFCKeditor = new FCKeditor('txtTexto','100%','400','MyToolbar');
            oFCKeditor.BasePath = "{$req_base}js/fckeditor/";
            oFCKeditor.Config['ToolbarStartExpanded'] = false ;
            oFCKeditor.Create();
        </script>
        <input type="submit" value={#aceptar#} />
        <input type="reset" value={#borrar#} />
        <input type="button" value={#cancelar#} onclick="document.location='{$req_base}index.php/cod.tipocons'">
      </form>
    </div>
  </div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}
