<div class="pac_info">
  <span class="intro">{#texto5#}</span>
  {if is_array($paciente)}
    {if isset($paciente.extension)}
      <div class="fotopers">
        <object data={$req_base}file.php/fotopers/{$paciente.id_paciente}/{$paciente.extension} type="image/{$paciente.extension}" height="80" width="80"></object>
      </div>
    {/if}
    <p>{$paciente.nombre} {$paciente.apellido} {$paciente.apellido2}</p>
    <p>{#texto6#} {$paciente.telefono_fijo} / {$paciente.telefono_movil} / {$paciente.telefono_trabajo}</p>
    <br />
    <fieldset><legend>{#texto7#}</legend>
    <p>{$paciente.alertas_medicas}</p>
    </fieldset>
    <fieldset><legend>{#texto8#}</legend>
    <p>{$paciente.observaciones}</p>
    </fieldset>
    <fieldset><legend>{#texto9#}</legend>
    <p>{$paciente.alto_riesgo}</p>
    </fieldset>
  {else}
    <p>{#texto10#}</p>
  {/if}
</div>
