{config_load file=$lang_file section="recetas"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

  <script type="text/javascript">
  <!--
  {literal}
  function loaded(){}
  {/literal} 
  // -->
  </script>

<div class="contenidos">
  <div class="col_central">
    <span class="intro">{#texto40#}</span>
    {include file=$tpl_path_base|cat:"gbdapp/recetas/pac_info.phtml"}
    {include file=$tpl_path_base|cat:"gbdapp/recetas/vis_info.phtml"}
    <br />
    {if is_array ($datos)}
    <fieldset><legend>{#texto24#}</legend>
      {$datos.resumen}
    </fieldset>
    <fieldset><legend>{#texto25#}</legend>
      {$datos.texto}
    </fieldset>
    <fieldset><legend>{#texto26#}</legend>
      {$datos.observaciones}
    </fieldset>
    {else}
      <p>{#texto23#}</p>
    {/if}
  </div>
  {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_header.phtml"}
    <li><input type="button" value="{#texto31#}" onclick="window.open('{$req_base}index.php/cod.verreceta/id.{$paciente.id_paciente}/vis.{$visita.id_visita}/r.{$datos.id_receta}/imp.1')"></li>
    <li><a href={$req_base}index.php/cod.borrareceta/id.{$paciente.id_paciente}/vis.{$visita.id_visita}/r.{$datos.id_receta}>{#texto36#}</a></li>
    <li><a href={$req_base}index.php/cod.historia/id.{$paciente.id_paciente}>{#texto37#}</a></li>
    <li><a href={$req_base}index.php/cod.verpac/id.{$paciente.id_paciente}>{#texto38#}</a></li>
    <li><a href={$req_base}index.php/cod.listapacientes>{#texto39#}</a></li>
  {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_footer.phtml"}
</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}