<div class="clin_info">
  <div class="logoclinica">
    <img src={$req_base}file.php/logo type="image/jpeg" width="100" height="110" />
  </div>
  <div class="numpres">
  <p>{#texto12#}</p>
  <input type="text" name="txtNumero" value="{$fact.numero}" disabled="disabled"/>
  <p>{#texto11#}{$fecha}</p>
  </div>
  {if is_array($clinica)}
  <p>{$clinica.nombre}</p>
  <p>{$clinica.especialidad}</p>
  <p>{#texto13#}{$clinica.nif}</p>
  <p>{$clinica.direccion}&nbsp;{$clinica.cp}&nbsp;{$clinica.ciudad}</p>
  <p>{#texto23#}{$clinica.telefono}</p>
  {/if}
</div>
{if is_array($paciente)}
  <div class="pac_info">
    <p>{#texto8#}<input type="text" name="txtNombre" value="{$fact.nombre_pagador}" /></p>
    <p>{#texto9#}{$paciente.direccion}</p>
    <p>{#texto59#}{$paciente.ciudad}</p>
    <p>{#texto58#}{$paciente.cp}</p>
    <p>{#texto60#}{$paciente.provincia}</p>
    <p>{#texto25#}<input type="text" name="txtDNI" value="{$fact.dni_pagador}" /></p>
  </div>
{/if}