{config_load file=$lang_file section="facturas"}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>{#tituloapp#}</title>
	<link href="{$req_base}css/estilos_aplicacion.css" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" href="{$img_path_base}favicon.ico">
</head>
<body class="imprimible">
    <span class="intro">{#texto33#}</span>
    {if is_array($datos)}
    {include file=$tpl_path_base|cat:"gbdapp/facturas/cabeceraver.phtml"}
    <table border="0" width="90%">
      <tr>
        <th colspan="6">&nbsp;</th>
      </tr>
      <tr>
        <td colspan="6">&nbsp;</td>
      </tr>
      <tr>
        <th>{#texto15#}</th>
        <th colspan="2">{#texto61#}</th>
        <th>{#texto14#}</th>
        <th>{#texto16#}</th>
        <th>&nbsp;</th>
      </tr>
      <tr>
        <td colspan="6" class="lineahor">&nbsp;</td>
      </tr>
      {counter assign=numlinea start=1 skip=1}
        {if is_array($lineas)}
          {foreach from=$lineas key=llave item=linea}
            <tr>
              <td>{$numlinea}.&nbsp;{$linea.servicio|default:#texto20#}</td>
              <td colspan="2">{$linea.texto}</td>
              <td align="center">{$linea.cantidad}</td>
              <td align="right">{$linea.total} €.</td>
            </tr>
          {counter}
          {/foreach}
        {/if}
      <tr>
        <td colspan="6" class="lineahor">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="3">{#texto20#}</th>
        <th colspan="2">{$datos.total} €.</th>
        <th>&nbsp;</th>
      </tr>
    </table>
  {else}
    <p>{#texto34#}</p>
  {/if}

</body>
</html>