{config_load file=$lang_file section="facturas"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<script language="JavaScript" src="{$req_base}js/TableManager.js" type="text/javascript"></script>

<script type="text/javascript">
var tableManager;
var services = [
    {foreach from=$servicios item=service key=key}
         new Option("{$service}", "{$key}"),
    {/foreach}
    ];
{literal}
<!--
function loaded(){
    tableManager = new TableManager(services, 'formTable', 'formulario', 'numLines', 'total');
}
{/literal}
</script>

<div class="contenidos">
  <div class="col_central">
    <span class="intro">{#texto7#}</span>
    <form id="formulario" enctype="multipart/form-data" method="POST" action={$req_base}index.php/cod.guardafact/id.{$paciente.id_paciente}>
    {include file=$tpl_path_base|cat:"gbdapp/facturas/cabecera.phtml"}
    {include file=$tpl_path_base|cat:"gbdapp/facturas/formTable.phtml"}
    </form>
  </div>
</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}