{config_load file=$lang_file section="facturas"}

{include file=$tpl_path_base|cat:"gbdapp/common/header.phtml"}

<script type="text/javascript">
{literal}
<!--
  function abrir(dir)
  {
    window.open(dir);
  }
-->
{/literal}
</script>

<div class="contenidos">
  <div class="col_central">
    <span class="intro">{#texto33#}</span>
    {if is_array($datos)}
    {include file=$tpl_path_base|cat:"gbdapp/facturas/cabeceraver.phtml"}
    <table border="0" width="100%">
      <tr>
        <th colspan="5">&nbsp;</th>
      </tr>
      <tr>
        <td colspan="5">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="2">{#texto15#}</th>
        <th>{#texto14#}</th>
        <th>{#texto16#}</th>
        <th>&nbsp;</th>
      </tr>
      <tr>
        <td colspan="5" class="lineahor">&nbsp;</td>
      </tr>
      {counter assign=numlinea start=1 skip=1}
        {if is_array($lineas)}
          {foreach from=$lineas key=llave item=linea}
            <tr>
              <td colspan="2">{$numlinea}.&nbsp;{$linea.servicio|default:#texto20#}</td>
              <td align="center">{$linea.cantidad}</td>
              <td align="right">{$linea.total} €.</td>
            </tr>
          {counter}
          {/foreach}
        {/if}
      <tr>
        <td colspan="5" class="lineahor">&nbsp;</td>
      </tr>
      <tr>
        <th colspan="3">{#texto20#}</th>
        <th>{$datos.total} €.</th>
        <th>&nbsp;</th>
      </tr>
    </table>
    <blockquote class="firmas">
      <object data={$req_base}file.php/fd type="image/jpg" width="100" height="100"></object>
      <br />
      <p>{#texto21#}</p>
    </blockquote>
  {else}
    <p>{#texto34#}</p>
  {/if}
  </div>
  {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_header.phtml"}
    {if is_array($datos)}
      <li><input type="button" value="{#texto35#}" onclick="abrir('{$req_base}index.php/cod.verfact/id.{$paciente.id_paciente}/fact.{$datos.id_factura}/imp.1')" /></li>
      <li><a href={$req_base}index.php/cod.borrafact/id.{$paciente.id_paciente}/fact.{$datos.id_factura}>{#texto36#}</a></li>
      <li><a href={$req_base}index.php/cod.verpac/id.{$paciente.id_paciente}>{#texto49#}</a></li>
    {/if}
  {include file=$tpl_path_base|cat:"gbdapp/common/recuadro_footer.phtml"}
</div>

{include file=$tpl_path_base|cat:"gbdapp/common/footer.phtml"}